scoring_engine/web/views/about.py
from flask import Blueprint, render_template
from scoring_engine.version import version
from scoring_engine.models.setting import Setting

mod = Blueprint('about', __name__)


@mod.route('/about')
def about():
    about_content = Setting.get_setting('about_page_content').value
    return render_template('about.html', version=version, about_content=about_content)

scoring_engine/web/views/auth.py
import uuid
from flask import flash, redirect, request, url_for, g, Blueprint, render_template
from flask_login import current_user, login_user, logout_user, LoginManager, login_required
from flask_wtf import FlaskForm

from wtforms import PasswordField, StringField
from wtforms.validators import InputRequired

from sqlalchemy.orm.exc import NoResultFound

from scoring_engine.db import session
from scoring_engine.models.user import User

from scoring_engine.web import app

mod = Blueprint('auth', __name__)
mod.secret_key = str(uuid.uuid4())

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'auth.login'
login_manager.login_message_category = 'info'
login_manager.session_protection = 'strong'


@login_manager.user_loader
def load_user(id):
    return session.query(User).get(int(id))


@app.before_request
def get_current_user():
    g.user = current_user


# Creating our login form
class LoginForm(FlaskForm):
    username = StringField('inputUsername', [InputRequired()], render_kw={"class": "form-control", "placeholder": "Username", "required": "true", "autofocus": "true"})
    password = PasswordField('inputUsername', [InputRequired()], render_kw={"class": "form-control", "placeholder": "Password", "required": "true"})


@mod.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash('You are already logged in.', 'info')
        return redirect(url_for("welcome.home"))

    form = LoginForm()

    if form.errors:
        flash(form.errors, 'danger')
        return render_template('login.html', form=form)

    if form.validate_on_submit():
        username = request.form.get('username')
        password = request.form.get('password')

        try:
            user = session.query(User).filter(User.username == username).one()
        except NoResultFound:
            flash('Invalid username or password. Please try again.', 'danger')
            return render_template('login.html', form=form)

        if User.generate_hash(password, user.password) == user.password:
            user.authenticated = True
            session.add(user)
            session.commit()
            login_user(user, remember=True)

            if user.is_white_team:
                return redirect(request.values.get('next') or url_for("admin.status"))
            elif user.is_blue_team:
                return redirect(request.values.get('next') or url_for("services.home"))
            else:
                return redirect(request.values.get('next') or url_for("overview.home"))
        else:
            flash('Invalid username or password. Please try again.', 'danger')
            return render_template('login.html', form=form)

    return render_template('login.html', form=form)


@mod.route('/unauthorized')
def unauthorized():
    return render_template('unauthorized.html')


@mod.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    session.add(user)
    session.commit()
    logout_user()
    flash('You have successfully logged out.', 'success')
    return redirect(url_for('auth.login'))

scoring_engine/web/views/overview.py
from flask import Blueprint, render_template

from scoring_engine.models.team import Team

mod = Blueprint("overview", __name__)


@mod.route("/overview")
def home():
    return render_template("overview.html", teams=Team.get_all_blue_teams())

scoring_engine/web/views/profile.py
from flask import Blueprint, render_template
from flask_login import login_required

mod = Blueprint('profile', __name__)


@mod.route('/profile')
@login_required
def home():
    return render_template('profile.html')

scoring_engine/web/views/scoreboard.py
from flask import Blueprint, render_template

mod = Blueprint('scoreboard', __name__)


@mod.route('/scoreboard')
def home():
    return render_template('scoreboard.html')

scoring_engine/web/views/services.py
from flask import Blueprint, render_template, url_for, redirect
from flask_login import login_required, current_user
from scoring_engine.models.service import Service
from scoring_engine.models.setting import Setting
from scoring_engine.db import session


mod = Blueprint('services', __name__)


@mod.route('/services')
@login_required
def home():
    if not current_user.is_blue_team:
        return redirect(url_for('auth.unauthorized'))
    return render_template('services.html', team_name=current_user.team.name, team_id=current_user.team.id)


@mod.route('/service/<id>')
@login_required
def service(id):
    service = session.query(Service).get(id)
    if service is None or not current_user.team == service.team:
        return redirect(url_for('auth.unauthorized'))
    modify_hostname_setting = Setting.get_setting('blue_team_update_hostname').value
    modify_port_setting = Setting.get_setting('blue_team_update_port').value
    modify_account_usernames_setting = Setting.get_setting('blue_team_update_account_usernames').value
    modify_account_passwords_setting = Setting.get_setting('blue_team_update_account_passwords').value

    return render_template(
        'service.html',
        id=id,
        service=service,
        modify_hostname_setting=modify_hostname_setting,
        modify_port_setting=modify_port_setting,
        modify_account_passwords_setting=modify_account_passwords_setting,
        modify_account_usernames_setting=modify_account_usernames_setting
    )

scoring_engine/web/views/welcome.py
from flask import Blueprint, render_template

from scoring_engine.models.setting import Setting

mod = Blueprint('welcome', __name__)


@mod.route('/')
@mod.route("/index")
def home():
    welcome_content = Setting.get_setting('welcome_page_content').value
    return render_template('welcome.html', welcome_content=welcome_content)

scoring_engine/web/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}
<div class="container md-page" style="padding-bottom: 0px;">
  <div class="row">
  {{about_content|safe}}
  </div>
  <br>
  <div class="col-sm-8 col-sm-offset-2 text-center" >
    <ul class="list-inline center-block">
      <li><h5><a href="https://scoringengine.readthedocs.io/en/latest/installation.html">Setup your own!</a></h5></li>
      <li><h5>Version: {{version}}</h5></li>
      <li><h5><a href="https://github.com/scoringengine/scoringengine/issues/new">File a bug</a></h5></li>
    </ul>
  </div>
</div>
{% endblock %}

scoring_engine/web/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %}
    <title>Scoring Engine - {% block title %}{% endblock %}</title>
    <script src="{{ url_for('static', filename='vendor/js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/js/bootstrap.min.js') }}"></script>
    {% endblock %}
    <link href="{{ url_for('static', filename='vendor/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/css/bootstrap-glyphicons.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
  </head>
  {% if 'unauthorized' in request.path %}
  <body style="background-color: red">
  {% else %}
  <body style="background-color: #f9f9f9;">
  {% endif %}
    <script>
      $(document).ready (function(){
        $("#alert-info").fadeTo(2000, 500).slideUp(500, function(){
          $("#alert-info").slideUp(500);
        });
      });
    </script>

    {% for category, message in get_flashed_messages(with_categories=true) %}
      <div class="alert alert-{{category}} alert-dismissable alert-fixed" id="alert-info" role="alert" style="margin-bottom: 0px">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <strong>{{ message }}</strong>
      </div>
    {% endfor %}

    {% if "admin" in request.path %}
    <nav class="navbar navbar-collapse navbar-inverse" style="border-radius: 0 !important">
    <!-- <nav class="collapse navbar-collapse navbar-inverse" style="border-radius: 0 !important">-->
    {% else %}
    <nav class="navbar navbar-collapse navbar-inverse" style="border-radius: 0 !important">
    {% endif %}
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Scoring Engine</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="">
          <ul class="nav navbar-nav">
            <li class="navbar-item {% if request.path == '/scoreboard' %}active{% endif %}"><a class="nav-link" href="{{ url_for('scoreboard.home') }}">Scoreboard</a></li>
            <li class="navbar-item {% if request.path == '/overview' %}active{% endif %}"><a class="nav-link"  href="{{ url_for('overview.home') }}">Overview</a></li>
            {% if current_user.is_authenticated %}
              {% if current_user.is_blue_team %}
                <li class="navbar-item {% if request.path == '/services' %}active{% endif %}"><a class="nav-link"  href="{{ url_for('services.home') }}">Services</a></li>
              {% endif %}
              {% if current_user.is_white_team %}
              <li class="navbar-item {% if 'admin' in request.path %}active{% endif %}"><a class="nav-link"  href="{{ url_for('admin.status') }}">Admin</a></li>
              {% endif %}
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if not current_user.is_authenticated %}
            <li class="navbar-item"><a href="{{ url_for('auth.login') }}">Login</a></li>
            {% else %}
            <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle navbar-item" style="margin-right: 20px;">{{ current_user.get_username }} <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('profile.home') }}">Profile</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
              </ul>
            </li>
            {% endif %}
            <li class="navbar-item"><a href="{{ url_for('about.about') }}">About</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!--/.container-fluid -->
    </nav>
    {% block content %}
    {% endblock %}
  </body>
</html>

scoring_engine/web/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/signin.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container md-page">
    <form method="POST" role="form" class="form-signin">
        {{ form.csrf_token }}
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputUsername" class="sr-only">Username</label>
        {{ form.username() }}
        <label for="inputPassword" class="sr-only">Password</label>
        {{ form.password() }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
</div>
{% endblock %}

scoring_engine/web/templates/overview.html
{% extends 'base.html' %}
{% block title %}Overview{% endblock %}
{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='vendor/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/js/dataTables.bootstrap.min.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/css/dataTables.bootstrap.min.css') }}" />
{% endblock %}
{% block content %}
<div class="container-fluid md-page">
    <div class="row">
        <h2 id="round_number" class="text-center"></h2>
        <h4 id="round_start" class="text-center"></h4>
    </div>
    <div class="row">
        <table id="overview" class="table table-striped table-bordered table-compact" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th></th>
                    {% for team in teams %}
                    <th>{{ team.name }}</th>
                    {% endfor %}
                </tr>
            </thead>
        </table>
        <script>
            function refreshheader() {
                $.ajax({
                    cache: false,
                    url: '/api/overview/get_round_data',
                    dataType: 'json',
                    success: function (data) {
                        $('#round_number').text("Round " + data.number);
                        $('#round_start').text(data.round_start);
                    }
                });
            }

            // Populate services table
            var overview = $('#overview').DataTable({
                'ajax': '/api/overview/get_data',
                'paging': false,
                'bSort': false,
                'info': false,
                'searching': false,
                'scrollX': true,
                'columnDefs': [
                    { "width": "10%", "targets": 0 }
                ],
                'createdRow': function (row, data, index) {
                    $('td', row).each(function () {
                        var value = $(this).html();
                        var column_num = $(this).index();
                        switch (index) {
                            // Current Score
                            case 0:
                                if (column_num == 0) {
                                    var html_str = `<span style="font-weight:bold">${value}</span>`
                                    $(this).html(html_str);
                                } else {
                                    var html_str = parseFloat(`${value}`).toLocaleString();
                                    $(this).html(html_str);
                                }
                                break;
                            // Current Place
                            case 1:
                                if (column_num == 0) {
                                    html_str = `<span style="font-weight:bold">${value}</span>`
                                    $(this).html(html_str);
                                    // Add Some Ribbons
                                } else {
                                    if (value == 1) {
                                        $(this).html(`${value} <i class="glyphicon glyphicon-tags" style="color: #C98910"></i>`);
                                    } else if (value == 2) {
                                        $(this).html(`${value} <i class="glyphicon glyphicon-tags" style="color: #A8A8A8"></i>`);
                                    } else if (value == 3) {
                                        $(this).html(`${value} <i class="glyphicon glyphicon-tags" style="color: #965A38"></i>`);
                                    }
                                }
                                break;
                            case 2:
                                // Up and down services ratio
                                if (column_num == 0) {
                                    html_str = `<span style="font-weight:bold">${value}</span>`
                                    $(this).html(html_str);
                                } else {
                                    html_str = `${value}`
                                    $(this).html(html_str);
                                }
                                break;
                            default:
                                // Service Name
                                if (column_num == 0) {
                                    html_str = `<span style="font-weight:bold">${value}</span>`
                                    $(this).html(html_str);
                                    break;
                                }

                                if (value == 'true') {
                                    var image_icon = 'glyphicon-ok';
                                    var image_color = 'green';
                                }
                                else if (value == 'false') {
                                    var image_icon = 'glyphicon-remove';
                                    var image_color = 'red';
                                }
                                else {
                                    image_icon = 'glyphicon-question-sign';
                                    image_color = 'black';
                                }

                                html_str = `<span class="glyphicon ${image_icon}" style="color:${image_color}"></span>`;
                                $(this).html(html_str);
                        }
                    })
                }
            });

            $(document).ready(function () {
                // Disable datatables error reporting
                $.fn.dataTable.ext.errMode = 'none';

                // Populate our header
                refreshheader();
                setInterval(function () {
                    refreshheader()
                }, 30000);

                setInterval(function () {
                    overview.ajax.reload();
                }, 30000);
            });
        </script>
    </div>
</div>
{% endblock %}

scoring_engine/web/templates/profile.html
{% extends 'base.html' %}
{% block title %}{{current_user.username}}{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container md-page">
  <div class="row">
    <h3>Name: {{current_user.username}}</h3>
    <h4>Team Color: {{current_user.team.color}}</h4>
    <div class="card">
      <h2 class="text-center">Update Password</h2>
      <form method="POST" action="{{url_for('api.profile_update_password')}}" role="form" class="form-signin">
        <input type="hidden" name="user_id" value="{{current_user.id}}">
        <div class="form-group">
          <input type="password" class="form-control" name="currentpassword" id="currentPassword" placeholder="Current Password" required>
        </div>
        <div class="form-group">
          <input type="password" class="form-control" name="password" id="inputPassword" placeholder="New Password" required>
        </div>
        <div class="form-group">
          <input type="password" class="form-control" name="confirmedpassword" id="inputConfirmedPassword" placeholder="Confirmed Password" required>
        </div>
        <button type="submit" class="btn btn-primary center-block">Update Password</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

scoring_engine/web/templates/scoreboard.html
{% extends "base.html" %}
{% block title %}Scoreboard{% endblock %}
{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='vendor/js/echarts.min.js') }}"></script>
{% endblock %}
{% block content %}
<div class="container md-page">
    <div id="teamBar" style="width: 100%; height:400px;"></div>
    <hr>
    <div id="teamLine" style="width: 100%; height:400px;"></div>
    <script>
        // Bar chart for all teams
        var teamBarChart = echarts.init(document.getElementById('teamBar'));
        teamBarChart.showLoading();

        const barList = [];
        $.get('/api/scoreboard/get_bar_data').done(function(data) {
            echarts.util.each(data.scores, function(score, index) {
                barList.push({
                    value: score,
                    itemStyle: {
                        color: data.colors[index]
                    }
                });
            });
            teamBarChart.hideLoading();
            teamBarChart.setOption({
                tooltip: {
                    trigger: 'axis'
                },
                grid: {
                    left: '3%',
                    right: '4%',
                    bottom: '3%',
                    containLabel: true
                },
                xAxis: [
                    {
                        type: 'category',
                        data: data.labels,
                    }
                ],
                yAxis: {
                    type: 'value'
                },
                series: [
                    {
                    data: barList,
                    type: 'bar'
                    }
                ]
            });
        });

        // Update chart every 30 seconds
        setInterval(function () {
            const barList = [];
            $.get('/api/scoreboard/get_bar_data').done(function(data) {
                echarts.util.each(data.scores, function(score, index) {
                    barList.push({
                        value: score,
                        itemStyle: {
                            color: data.colors[index]
                        }
                    });
                });
                teamBarChart.setOption({
                    series: [{
                        data: barList,
                    }]
                });
            });
        }, 30000);
    </script>
    <script>
        // Line chart for all teams
        var teamLineChart = echarts.init(document.getElementById('teamLine'));
        teamLineChart.showLoading();

        const seriesList = [];
        $.get('/api/scoreboard/get_line_data').done(function(data) {
            echarts.util.each(data.team, function(team) {
                seriesList.push({
                    name: team.name,
                    type: 'line',
                    data: team.scores,
                    itemStyle: {
                        color: team.color
                    }
                });
            });
            teamLineChart.hideLoading();
            teamLineChart.setOption({
                tooltip: {
                    trigger: 'axis'
                },
                grid: {
                    left: '3%',
                    right: '4%',
                    bottom: '3%',
                    containLabel: true
                },
                xAxis: {
                    type: 'category',
                    boundaryGap: false,
                    data: data.rounds
                },
                yAxis: {
                    type: 'value'
                },
                series: seriesList,
            });
        });

        // Update chart every 30 seconds
        setInterval(function () {
            const seriesList = [];
            $.get('/api/scoreboard/get_line_data').done(function(data) {
                echarts.util.each(data.team, function(team) {
                    seriesList.push({
                        name: team.name,
                        type: 'line',
                        data: team.scores,
                    });
                });
                teamLineChart.setOption({
                    series: seriesList,
                });
            });
        }, 30000);
    </script>
</div>
{% endblock %}

scoring_engine/web/templates/services.html
{% extends 'base.html' %}
{% block title %}Services{% endblock %}
{% block head %}
    {{ super() }}
    <script src="{{ url_for('static', filename='vendor/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/js/dataTables.bootstrap.min.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='vendor/css/dataTables.bootstrap.min.css') }}" />
{% endblock %}
{% block content %}
<div class="container md-page">
    <div class="row">
        <h3>{{team_name}}</h3>
        <h5 id="team_place">Place: </h5>
        <h5 id="team_current_score">Score: </h5>
    </div>
    <div class="row">
        <table id="services" class="table table-striped table-bordered table-compact" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th><div title="Name of Service">Service</div></th>
                    <th><div title="Host/ip of the service">Host</div></th>
                    <th><div title="Port of the service">Port</div></th>
                    <th><div title="Current check result of the service">Status</div></th>
                    <th><div title="Overall rank compared to other blue teams">Rank</div></th>
                    <th><div title="Overall score earned for this service">Score Earned</div></th>
                    <th><div title="Maximum possible score">Max Score</div></th>
                    <th><div title="Percent of overall score earned">% Earned</div></th>
                    <th><div title="Points per successful check">Pts Per Check</div></th>
                    <th><div title="Last 10 results">Trending</div></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
        <script>
            function refreshteamdata() {
                $.ajax({
                    cache: false,
                    url: '/api/team/{{team_id}}/stats',
                    dataType: 'json',
                    success: function(data) {
                        $('#team_place').text("Place: " + data.place);
                        $('#team_current_score').text("Score: " + parseFloat(data.current_score).toLocaleString());
                    }
                });
            }

            $(document).ready(function() {
                refreshteamdata();
                setInterval(function(){
                    refreshteamdata()
                }, 30000);

                // Disable datatables error reporting
                $.fn.dataTable.ext.errMode = 'none';

                var table = $('#services')
                    .on('error.dt', function (e, settings, techNote, message) {
                        console.log('An error has been reported by DataTables: ', message);
                    })
                    .DataTable({
                        'paging': false,
                        'bFilter': false,
                        'bInfo': false,
                        "ajax": "/api/team/{{team_id}}/services",
                        "order": [],
                        "columns": [
                            {
                                "data": null,
                                "render": function( data ) {
                                    return '<a href="/service/' + data.service_id + '">' + data.service_name + '</a>';
                                }
                            },
                            { "data": "host" },
                            { "data": "port" },
                            {
                                "data": null,
                                "render": function( data ) {
                                    var span_str = '<span class="label label-'
                                    var label_level = 'default'
                                    var label_str = 'Undetermined'
                                    if ( data.check == "UP" ) {
                                        label_level = 'success'
                                        label_str = 'UP'
                                    } else if ( data.check == "DOWN" ) {
                                        label_level = 'danger'
                                        label_str = 'DOWN'
                                    }
                                    span_str += label_level + '">' + label_str + '</span>'
                                    return span_str;
                                }
                            },
                            { "data": "rank" },
                            {
                                "data": "score_earned",
                                "render": function( data ) {
                                    return parseFloat(data).toLocaleString()
                                }
                            },
                            {
                                "data": "max_score",
                                "render": function( data ) {
                                    return parseFloat(data).toLocaleString()
                                }
                            },
                            { "data": "percent_earned" },
                            { "data": "pts_per_check" },
                            {
                                "data": null,
                                "orderable": false,
                                "render": function( data ) {
                                    var last_ten_checks = '<div align="right">'
                                    for (var index in data.last_ten_checks) {
                                        if ( data.last_ten_checks[index] == true ) {
                                            last_ten_checks += '<span class="glyphicon glyphicon-ok" style="color:green"></span>';
                                        }
                                        else {
                                        last_ten_checks += '<span class="glyphicon glyphicon-remove" style="color:red"></span>';
                                        }
                                    }
                                    return '</div>' + last_ten_checks;
                                }
                            },
                        ],
                    });
                setInterval( function () {
                    table.ajax.reload();
                }, 30000 );
            } );
        </script>
    </div>
</div>
{% endblock %}

scoring_engine/web/templates/unauthorized.html
{% extends 'base.html' %}
{% block title %}Unauthorized{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
      <img class="center-block" style="border-style: solid; border-width: 5px;" src="{{ url_for('static', filename='images/unauthorized.gif') }}">
  </div>
</div>
{% endblock %}

scoring_engine/web/templates/welcome.html
{% extends 'base.html' %}
{% block title %}Welcome{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container md-page">
  {{welcome_content|safe}}
</div>
{% endblock %}